api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt
              
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /custom
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
#      caserver: https://acme-staging-v02.api.letsencrypt.org/directory # for test only
      email: admin@example.com
      storage: acme.json
      tlschallenge: true
      httpChallenge:
        entryPoint: web
